version: "3.1"
services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=officerent
    volumes:
      - ./docker/data/:/var/lib/mysql
      - ./ops/sql:/tmp/scripts/sql
    ports:
      - 3306:3306
    command: mysqld --init-file="/tmp/scripts/sql/init.sql"